name: Test

on: [push]

jobs:
  job-test:
    name: Run unit tests
    runs-on: macOS-latest    
    steps:
    - uses: actions/checkout@v1

    - name: Install needed software
      run: |
        gem install xcpretty 
        gem install bundler:1.17.2
        brew install swiftlint

    - name: Run unit tests
      run: fastlane tests